let perritos = [
    {
        nombre: "Leo",
        poderes: ["dormir", "comer mucho", "Mega Ladrido", "Salto De Fuego"],
        description: "Leo, perro san bernardo. Un pancake radioactivo lo mordió y se convirtió en un perro con poderes",
        raza: "Shih-Tzu",
        imagen: "https://placedog.net/500/280?id=1",
        universo: "Perroid004",
        aura: 10000,
        activo: true,
        altura: 2.00,
        edad: 5,
    },
    {
        nombre: "Mochi",
        poderes: ["teletransportar juguetes", "orejas radar"],
        description: "Mochi lamió un enchufe con sabor a matcha y desde entonces teletransporta cualquier objeto del tamaño de una pelota",
        raza: "Golden Retriever",
        imagen: "https://placedog.net/500/280?id=2",
        universo: "Perroid011",
        aura: 4200,
        activo: true,
        altura: 0.38,
        edad: 3,
    },
    {
        nombre: "Rocko",
        poderes: ["congelar el tiempo (3s)", "siesta táctica"],
        description: "Rocko se tragó una batería de reloj mientras dormía la siesta y ahora puede congelar el tiempo por 3 segundos exactos",
        raza: "Golden Retriever",
        imagen: "https://placedog.net/500/280?id=3",
        universo: "Perroid007",
        aura: 6100,
        activo: false,
        altura: 0.32,
        edad: 4,
    },
    {
        nombre: "Nube",
        poderes: ["electricidad estática", "pelaje escudo"],
        description: "Nube durmió una noche entera bajo una antena de wifi rota y despertó controlando la electricidad estática",
        raza: "Labrador",
        imagen: "https://placedog.net/500/280?id=4",
        universo: "Perroid002",
        aura: 8300,
        activo: true,
        altura: 0.56,
        edad: 2,
    },
    {
        nombre: "Trueno",
        poderes: ["rayos con la cola", "ladrido sónico"],
        description: "Trueno mordió un cable pelado en plena tormenta y ahora genera rayos cada vez que mueve la cola",
        raza: "Lobo Siberiano",
        imagen: "https://placedog.net/500/280?id=5",
        universo: "Perroid015",
        aura: 15400,
        activo: true,
        altura: 0.62,
        edad: 6,
    },
    {
        nombre: "Pixel",
        poderes: ["pausar la realidad", "vidas extra"],
        description: "Pixel se cayó dentro de una consola retro abierta y ahora puede pausar la realidad como si fuera un videojuego",
        raza: "Weimaraner",
        imagen: "https://placedog.net/500/280?id=6",
        universo: "Perroid099",
        aura: 9900,
        activo: true,
        altura: 0.58,
        edad: 3,
    },
    {
        nombre: "Canela",
        poderes: ["escupir fuego al estornudar", "aliento picante"],
        description: "Canela se comió un chile fantasma por accidente y ahora escupe fuego cada vez que estornuda",
        raza: "Schnauzer",
        imagen: "https://placedog.net/500/280?id=7",
        universo: "Perroid021",
        aura: 3300,
        activo: true,
        altura: 0.18,
        edad: 7,
    },
    {
        nombre: "Bruno",
        poderes: ["invisibilidad al bostezar", "olfato fantasma"],
        description: "Bruno encontró un anillo enterrado en el jardín y ahora se vuelve invisible cada vez que bosteza",
        raza: "Border Collie",
        imagen: "https://placedog.net/500/280?id=8",
        universo: "Perroid033",
        aura: 7200,
        activo: false,
        altura: 0.57,
        edad: 8,
    },
    {
        nombre: "Luna",
        poderes: ["controlar las mareas", "aullido eclipse"],
        description: "Luna aulló tan fuerte durante un eclipse que absorbió parte de los poderes de la luna, ahora controla las mareas",
        raza: "Golden Retriever",
        imagen: "https://placedog.net/500/280?id=9",
        universo: "Perroid044",
        aura: 12800,
        activo: true,
        altura: 0.56,
        edad: 4,
    },
    {
        nombre: "Tofu",
        poderes: ["rebote infinito", "esquiva ataques"],
        description: "Tofu cayó sin querer en una fuente de gelatina radioactiva del laboratorio del vecino y ahora rebota como resorte sin cansarse",
        raza: "Braco Alemán",
        imagen: "https://placedog.net/500/280?id=10",
        universo: "Perroid058",
        aura: 5600,
        activo: true,
        altura: 0.35,
        edad: 2,
    },
    {
        nombre: "Max",
        poderes: ["clonarse temporalmente", "velocidad x2"],
        description: "Max persiguió una ardilla directo hacia un portal dimensional en el parque y ahora puede clonarse por un rato",
        raza: "Schnauzer",
        imagen: "https://placedog.net/500/280?id=11",
        universo: "Perroid066",
        aura: 11100,
        activo: true,
        altura: 0.58,
        edad: 5,
    },
    {
        nombre: "Kiwi",
        poderes: ["estirarse como chicle", "colarse por rendijas"],
        description: "Kiwi olfateó un frasco de pegamento extraterrestre caído de un satélite y ahora estira su cuerpo como si fuera chicle",
        raza: "Pastor Alemán",
        imagen: "https://placedog.net/500/280?id=12",
        universo: "Perroid077",
        aura: 4800,
        activo: true,
        altura: 0.33,
        edad: 3,
    },
];